### ISSUE TITLE
US-12: My Courses (1)

### ISSUE THREAD

**Issue by afiorito** [a-fiorito/NoteShare#19]
**Description:** As a user I should be able select the course I currently want to see documents for in order to reduce the number of documents to search through.

**Tasks:** On the main dashboard, the sidebar will be loaded with courses from the database. Once the courses are loaded, the user will be able to select which course theyd like to see documents for.
* Create sidebar (1hr)
* Send an HTTP request to load courses from the database (0.5hr)
* Allow user to select a course for which they like to view courses for (0.5hr)
* Create a footer (0.5hr)

**Priority:** Should be completed in Sprint 2. This feature is essential for the organization of the documents on the main dashboard.

**Risk:** The sidebar will have to be strongly linked to the main documents viewer.

**Unit Test**: [__tests__/my-courses.test.js](https://github.com/a-fiorito/NoteShare/blob/master/__tests__/my-courses.test.js)
**Acceptance Test**: [Documentation/Acceptance Tests/us-12.txt](https://github.com/a-fiorito/NoteShare/blob/master/Documentation/Acceptance%20Tests/us-12.txt)

**Comment by momo2793** [comment]
sounds good
